# Generated by Django 5.2.3 on 2025-06-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_founditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
